# File to configure continuous deployment
# Will be triggered once there is a push to github
# This is for Google Cloud Run through Google Cloud Build
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/water-treatment-twin:latest", "django/watertreatment"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/water-treatment-twin:latest"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "water-treatment-twin",
        "--image",
        "gcr.io/$PROJECT_ID/water-treatment-twin:latest",
        "--region",
        "europe-west1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--port=8000"
      ]

# Need to find another way for Google App Engine for it to interact with creating new database