# File to configure continuous deployment
# Will be triggered once there is a push to github
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/python-django:latest", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/python-django"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "gcr.io/$PROJECT_ID/python-django:latest",
        "--region",
        "europe-west1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]