# Generated by Django 4.1.3 on 2022-12-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('elemID', models.IntegerField(blank=True, db_column='elemID', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('params', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'document',
                'managed': False,
            },
        ),
    ]
