# Generated by Django 4.1.3 on 2022-11-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='elementID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
