# Generated by Django 4.1.3 on 2023-04-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_flow', models.IntegerField(verbose_name='Average Flow')),
                ('average_tss', models.IntegerField(verbose_name='Amount of particulate in waste water')),
                ('sim_length', models.IntegerField(verbose_name='Length of time for simulation in seconds/minutes')),
                ('initial_particulates', models.IntegerField(verbose_name='Amount of pre-existing particulate in tanks')),
                ('testing', models.BooleanField(verbose_name='Is this part of testing?')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
