name: Bug Fix
description: Track the bugs that you fix
title: "[Bug]: "
body: 
  - type: input
    id: feature-name
    attributes:
      label: Feature Name
      description: What feature has the bug?
      placeholder: e.g. Simulation, Visualisation, etc.
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Describe what the bug you are fixing is, and what the intended behaviour is
      placeholder: e.g. A is doing X but should be doing Y
    validations:
      required: false
